services:
  postgres:
    image: 'postgres:latest'
    restart: "no"
    environment:
     POSTGRES_PASSWORD: postgres

    ports:
      - "6432:5432"
    volumes:
      - ./files/pg_data:/var/lib/postgresql/data
